import { ToolsCreateMigrationTemplateInput } from '@api/graphql';

export const migrations: ToolsCreateMigrationTemplateInput[] = [
    /* {
        id      : '1cd0c79e-b83b-4ebf-b112-063669703cdc',
        name    : 'IAM Permissions',
        version : 'v1.0.0',
        sort    : 1,
        upScript: `
INSERT INTO public."IamPermission" (id, "name", "boundedContextId")
VALUES('752a72f1-940d-49f7-9702-44f7b95a7ff5'::uuid, 'aurora.test', 'f405132f-786d-4a6a-a262-0e6a6518aec3'::uuid);
        `,
        downScript: `
DELETE FROM public."IamPermission"
WHERE id='752a72f1-940d-49f7-9702-44f7b95a7ff5'::uuid;
        `,
    }, */
    {
        id      : '296402f5-8dd4-408e-a61f-14eac11f10e1',
        name    : 'Add rowId to IamAccount',
        version : '0.0.1',
        sort    : 1,
        upScript: `
            ALTER TABLE public."IamAccount" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamAccount"
            )
            UPDATE public."IamAccount" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamAccount"','rowId'), (SELECT MAX("rowId") FROM public."IamAccount"), true);

            ALTER TABLE public."IamAccount" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_account_row_id ON public."IamAccount" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_account_row_id";
            ALTER TABLE public."IamAccount" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '3d246816-dcf7-4c62-8d95-6a95c4c87030',
        name    : 'Add rowId to IamBoundedContext',
        version : '0.0.1',
        sort    : 2,
        upScript: `
            ALTER TABLE public."IamBoundedContext" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamBoundedContext"
            )
            UPDATE public."IamBoundedContext" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamBoundedContext"','rowId'), (SELECT MAX("rowId") FROM public."IamBoundedContext"), true);

            ALTER TABLE public."IamBoundedContext" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_bounded_context_row_id ON public."IamBoundedContext" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_bounded_context_row_id";
            ALTER TABLE public."IamBoundedContext" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '10041006-56df-4dbd-849e-7ca590e59106',
        name    : 'Add rowId to IamPermission',
        version : '0.0.1',
        sort    : 3,
        upScript: `
            ALTER TABLE public."IamPermission" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamPermission"
            )
            UPDATE public."IamPermission" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamPermission"','rowId'), (SELECT MAX("rowId") FROM public."IamPermission"), true);

            ALTER TABLE public."IamPermission" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_permission_row_id ON public."IamPermission" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_permission_row_id";
            ALTER TABLE public."IamPermission" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'ed53e667-ad29-4054-827d-4bd135b26b59',
        name    : 'Add rowId to IamRole',
        version : '0.0.1',
        sort    : 4,
        upScript: `
            ALTER TABLE public."IamRole" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamRole"
            )
            UPDATE public."IamRole" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamRole"','rowId'), (SELECT MAX("rowId") FROM public."IamRole"), true);

            ALTER TABLE public."IamRole" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_role_row_id ON public."IamRole" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_role_row_id";
            ALTER TABLE public."IamRole" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '2d71ab42-f073-4772-9fbb-22f4ee6e1178',
        name    : 'Add rowId to IamTag',
        version : '0.0.1',
        sort    : 5,
        upScript: `
            ALTER TABLE public."IamTag" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamTag"
            )
            UPDATE public."IamTag" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamTag"','rowId'), (SELECT MAX("rowId") FROM public."IamTag"), true);

            ALTER TABLE public."IamTag" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_tag_row_id ON public."IamTag" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_tag_row_id";
            ALTER TABLE public."IamTag" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'e82358c0-cfa1-449f-90b8-ca664c4195ca',
        name    : 'Add rowId to IamTenant',
        version : '0.0.1',
        sort    : 6,
        upScript: `
            ALTER TABLE public."IamTenant" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamTenant"
            )
            UPDATE public."IamTenant" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamTenant"','rowId'), (SELECT MAX("rowId") FROM public."IamTenant"), true);

            ALTER TABLE public."IamTenant" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_tenant_row_id ON public."IamTenant" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_tenant_row_id";
            ALTER TABLE public."IamTenant" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'f1833794-a67c-4e1a-8eaf-3036b4ff2a50',
        name    : 'Add rowId to IamUser',
        version : '0.0.1',
        sort    : 7,
        upScript: `
            ALTER TABLE public."IamUser" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamUser"
            )
            UPDATE public."IamUser" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamUser"','rowId'), (SELECT MAX("rowId") FROM public."IamUser"), true);

            ALTER TABLE public."IamUser" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_user_row_id ON public."IamUser" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_user_row_id";
            ALTER TABLE public."IamUser" DROP COLUMN IF EXISTS "rowId";
        `,
    },
];